// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mydataset_lane_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] in_r_address0;
output   in_r_ce0;
input  [15:0] in_r_q0;
output  [11:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [15:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ce0;
reg out_r_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] layers_3_bias_V_address0;
reg    layers_3_bias_V_ce0;
wire   [6:0] layers_3_bias_V_q0;
wire   [7:0] tmp_fu_174_p3;
reg   [7:0] tmp_reg_495;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln238_fu_200_p2;
reg   [0:0] icmp_ln238_reg_503;
wire   [0:0] icmp_ln237_fu_182_p2;
wire   [3:0] select_ln237_2_fu_230_p3;
reg   [3:0] select_ln237_2_reg_516;
wire   [0:0] and_ln237_fu_281_p2;
reg   [0:0] and_ln237_reg_522;
wire    ap_CS_fsm_state3;
wire   [4:0] select_ln238_fu_292_p3;
reg   [4:0] select_ln238_reg_528;
wire   [3:0] empty_185_fu_305_p1;
reg   [3:0] empty_185_reg_538;
wire   [3:0] add_ln246_fu_326_p2;
reg   [3:0] add_ln246_reg_544;
wire    ap_CS_fsm_state4;
wire   [3:0] select_ln238_2_fu_332_p3;
reg   [3:0] select_ln238_2_reg_549;
wire   [7:0] shl_ln_fu_343_p3;
reg   [7:0] shl_ln_reg_559;
wire   [9:0] p_shl_fu_352_p3;
reg   [9:0] p_shl_reg_564;
wire   [6:0] p_shl7_fu_360_p3;
reg   [6:0] p_shl7_reg_569;
wire   [10:0] p_mid138_fu_393_p2;
reg   [10:0] p_mid138_reg_574;
(* use_dsp48 = "no" *) wire   [11:0] add_ln240_fu_429_p2;
reg   [11:0] add_ln240_reg_579;
wire    ap_CS_fsm_state5;
wire    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start;
wire    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_done;
wire    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_idle;
wire    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_ready;
wire   [10:0] grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_in_r_address0;
wire    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_in_r_ce0;
wire   [15:0] grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_lhs_out;
wire    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_lhs_out_ap_vld;
reg    grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start_reg;
wire   [63:0] zext_ln239_fu_300_p1;
wire   [63:0] zext_ln240_fu_434_p1;
wire    ap_CS_fsm_state6;
reg   [4:0] oc_fu_78;
wire   [4:0] add_ln239_fu_309_p2;
reg   [3:0] w_fu_82;
reg   [8:0] indvar_flatten60_fu_86;
wire   [8:0] select_ln238_3_fu_244_p3;
reg   [3:0] h_fu_90;
wire   [3:0] select_ln237_1_fu_212_p3;
reg   [11:0] indvar_flatten86_fu_94;
wire   [11:0] add_ln237_fu_188_p2;
wire   [3:0] empty_184_fu_206_p2;
wire   [3:0] p_mid174_fu_224_p2;
wire   [8:0] add_ln238_fu_238_p2;
wire   [0:0] icmp_ln239_fu_275_p2;
wire   [0:0] xor_ln237_fu_270_p2;
wire   [0:0] or_ln238_fu_287_p2;
wire   [3:0] select_ln237_fu_320_p3;
wire   [3:0] p_mid120_fu_368_p2;
wire   [6:0] p_shl11_mid_fu_381_p3;
wire   [10:0] p_shl10_mid_fu_373_p3;
wire   [10:0] p_shl11_cast_mid136_fu_389_p1;
wire   [7:0] p_mid_fu_411_p3;
wire   [7:0] select_ln237_3_fu_405_p3;
wire   [7:0] select_ln238_1_fu_418_p3;
wire   [11:0] grp_fu_442_p3;
wire   [11:0] zext_ln238_fu_425_p1;
wire   [3:0] grp_fu_442_p0;
wire   [7:0] grp_fu_442_p1;
wire   [4:0] grp_fu_442_p2;
reg    grp_fu_442_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire   [11:0] grp_fu_442_p00;
wire   [11:0] grp_fu_442_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start_reg = 1'b0;
end

mydataset_lane_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixeeOg #(
    .DataWidth( 7 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
layers_3_bias_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layers_3_bias_V_address0),
    .ce0(layers_3_bias_V_ce0),
    .q0(layers_3_bias_V_q0)
);

mydataset_lane_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6 grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start),
    .ap_done(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_done),
    .ap_idle(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_idle),
    .ap_ready(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_ready),
    .sext_ln240(shl_ln_reg_559),
    .p_shl7(p_shl7_reg_569),
    .select_ln237_2(select_ln237_2_reg_516),
    .p_mid138(p_mid138_reg_574),
    .select_ln238_2(select_ln238_2_reg_549),
    .p_shl_cast(p_shl_reg_564),
    .in_r_address0(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_in_r_address0),
    .in_r_ce0(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_in_r_ce0),
    .in_r_q0(in_r_q0),
    .lhs_out(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_lhs_out),
    .lhs_out_ap_vld(grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_lhs_out_ap_vld)
);

mydataset_lane_mac_muladd_4ns_8ns_5ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mac_muladd_4ns_8ns_5ns_12_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_442_p0),
    .din1(grp_fu_442_p1),
    .din2(grp_fu_442_p2),
    .ce(grp_fu_442_ce),
    .dout(grp_fu_442_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_ready == 1'b1)) begin
            grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        h_fu_90 <= 4'd0;
    end else if (((icmp_ln237_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        h_fu_90 <= select_ln237_1_fu_212_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten60_fu_86 <= 9'd0;
    end else if (((icmp_ln237_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten60_fu_86 <= select_ln238_3_fu_244_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten86_fu_94 <= 12'd0;
    end else if (((icmp_ln237_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten86_fu_94 <= add_ln237_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oc_fu_78 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        oc_fu_78 <= add_ln239_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        w_fu_82 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        w_fu_82 <= select_ln238_2_fu_332_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln240_reg_579 <= add_ln240_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln246_reg_544 <= add_ln246_fu_326_p2;
        p_mid138_reg_574[10 : 3] <= p_mid138_fu_393_p2[10 : 3];
        p_shl7_reg_569[6 : 3] <= p_shl7_fu_360_p3[6 : 3];
        p_shl_reg_564[9 : 6] <= p_shl_fu_352_p3[9 : 6];
        select_ln238_2_reg_549 <= select_ln238_2_fu_332_p3;
        shl_ln_reg_559[7 : 1] <= shl_ln_fu_343_p3[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        and_ln237_reg_522 <= and_ln237_fu_281_p2;
        empty_185_reg_538 <= empty_185_fu_305_p1;
        select_ln238_reg_528 <= select_ln238_fu_292_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln238_reg_503 <= icmp_ln238_fu_200_p2;
        select_ln237_2_reg_516 <= select_ln237_2_fu_230_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_495[7 : 4] <= tmp_fu_174_p3[7 : 4];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln237_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln237_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state5) & (grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_done == 1'b1)))) begin
        grp_fu_442_ce = 1'b1;
    end else begin
        grp_fu_442_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layers_3_bias_V_ce0 = 1'b1;
    end else begin
        layers_3_bias_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln237_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln237_fu_188_p2 = (indvar_flatten86_fu_94 + 12'd1);

assign add_ln238_fu_238_p2 = (indvar_flatten60_fu_86 + 9'd1);

assign add_ln239_fu_309_p2 = (select_ln238_fu_292_p3 + 5'd1);

assign add_ln240_fu_429_p2 = (grp_fu_442_p3 + zext_ln238_fu_425_p1);

assign add_ln246_fu_326_p2 = (select_ln237_fu_320_p3 + 4'd1);

assign and_ln237_fu_281_p2 = (xor_ln237_fu_270_p2 & icmp_ln239_fu_275_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign empty_184_fu_206_p2 = (h_fu_90 + 4'd1);

assign empty_185_fu_305_p1 = select_ln238_fu_292_p3[3:0];

assign grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start = grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_ap_start_reg;

assign grp_fu_442_p0 = grp_fu_442_p00;

assign grp_fu_442_p00 = select_ln237_1_fu_212_p3;

assign grp_fu_442_p1 = 12'd208;

assign grp_fu_442_p2 = grp_fu_442_p20;

assign grp_fu_442_p20 = select_ln238_reg_528;

assign icmp_ln237_fu_182_p2 = ((indvar_flatten86_fu_94 == 12'd2704) ? 1'b1 : 1'b0);

assign icmp_ln238_fu_200_p2 = ((indvar_flatten60_fu_86 == 9'd208) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_275_p2 = ((oc_fu_78 == 5'd16) ? 1'b1 : 1'b0);

assign in_r_address0 = grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_in_r_address0;

assign in_r_ce0 = grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_in_r_ce0;

assign layers_3_bias_V_address0 = zext_ln239_fu_300_p1;

assign or_ln238_fu_287_p2 = (icmp_ln238_reg_503 | and_ln237_fu_281_p2);

assign out_r_address0 = zext_ln240_fu_434_p1;

assign out_r_d0 = grp_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_Pipeline_VITIS_LOOP_242_4_VITIS_LOOP_243_5_VITIS_LOOP_244_6_fu_128_lhs_out;

assign p_mid120_fu_368_p2 = ($signed(select_ln237_2_reg_516) + $signed(4'd15));

assign p_mid138_fu_393_p2 = (p_shl10_mid_fu_373_p3 - p_shl11_cast_mid136_fu_389_p1);

assign p_mid174_fu_224_p2 = (h_fu_90 + 4'd2);

assign p_mid_fu_411_p3 = {{add_ln246_reg_544}, {4'd0}};

assign p_shl10_mid_fu_373_p3 = {{p_mid120_fu_368_p2}, {7'd0}};

assign p_shl11_cast_mid136_fu_389_p1 = p_shl11_mid_fu_381_p3;

assign p_shl11_mid_fu_381_p3 = {{p_mid120_fu_368_p2}, {3'd0}};

assign p_shl7_fu_360_p3 = {{empty_185_reg_538}, {3'd0}};

assign p_shl_fu_352_p3 = {{empty_185_reg_538}, {6'd0}};

assign select_ln237_1_fu_212_p3 = ((icmp_ln238_fu_200_p2[0:0] == 1'b1) ? empty_184_fu_206_p2 : h_fu_90);

assign select_ln237_2_fu_230_p3 = ((icmp_ln238_fu_200_p2[0:0] == 1'b1) ? p_mid174_fu_224_p2 : empty_184_fu_206_p2);

assign select_ln237_3_fu_405_p3 = ((icmp_ln238_reg_503[0:0] == 1'b1) ? 8'd0 : tmp_reg_495);

assign select_ln237_fu_320_p3 = ((icmp_ln238_reg_503[0:0] == 1'b1) ? 4'd0 : w_fu_82);

assign select_ln238_1_fu_418_p3 = ((and_ln237_reg_522[0:0] == 1'b1) ? p_mid_fu_411_p3 : select_ln237_3_fu_405_p3);

assign select_ln238_2_fu_332_p3 = ((and_ln237_reg_522[0:0] == 1'b1) ? add_ln246_fu_326_p2 : select_ln237_fu_320_p3);

assign select_ln238_3_fu_244_p3 = ((icmp_ln238_fu_200_p2[0:0] == 1'b1) ? 9'd1 : add_ln238_fu_238_p2);

assign select_ln238_fu_292_p3 = ((or_ln238_fu_287_p2[0:0] == 1'b1) ? 5'd0 : oc_fu_78);

assign shl_ln_fu_343_p3 = {{layers_3_bias_V_q0}, {1'd0}};

assign tmp_fu_174_p3 = {{w_fu_82}, {4'd0}};

assign xor_ln237_fu_270_p2 = (icmp_ln238_reg_503 ^ 1'd1);

assign zext_ln238_fu_425_p1 = select_ln238_1_fu_418_p3;

assign zext_ln239_fu_300_p1 = select_ln238_fu_292_p3;

assign zext_ln240_fu_434_p1 = add_ln240_reg_579;

always @ (posedge ap_clk) begin
    tmp_reg_495[3:0] <= 4'b0000;
    shl_ln_reg_559[0] <= 1'b0;
    p_shl_reg_564[5:0] <= 6'b000000;
    p_shl7_reg_569[2:0] <= 3'b000;
    p_mid138_reg_574[2:0] <= 3'b000;
end

endmodule //mydataset_lane_Conv_ap_fixed_16_8_6_0_0_ap_fixed_16_8_6_0_0_ap_fixed_8_1_6_0_0_const_ap_fixed_8_1_6_0_0_const_8_15_15_16_13_13_3_1_0_s
